import { library } from '@fortawesome/fontawesome-svg-core';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
import {
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faAngleUp,
  faArrowLeft,
  faArrowRight,
  faBars,
  faBroadcastTower,
  faCheck,
  faCircle,
  faChartBar,
  faCrown,
  faExclamationCircle,
  faExternalLinkAlt,
  faFrown,
  faGrin,
  faLanguage,
  faMeh,
  faMehBlank,
  faMinus,
  faProjectDiagram,
  faQuestion,
  faSlash,
  faSmile,
  faTimes,
  faUndo,
  faUnlink,
  faUserFriends,
  faUserPlus,
} from '@fortawesome/free-solid-svg-icons';
import type { App } from 'vue';

export default function loadFontAwesome(app: App) {
  app.component('FontAwesomeIcon', FontAwesomeIcon);
  library.add(
    faAngleDown,
    faAngleLeft,
    faAngleRight,
    faAngleUp,
    faArrowLeft,
    faArrowRight,
    faBars,
    faBroadcastTower,
    faCheck,
    faCircle,
    faChartBar,
    faCrown,
    faExclamationCircle,
    faExternalLinkAlt,
    faFrown,
    faGrin,
    faLanguage,
    faMeh,
    faMehBlank,
    faMinus,
    faProjectDiagram,
    faQuestion,
    faSlash,
    faSmile,
    faTimes,
    faUndo,
    faUnlink,
    faUserFriends,
    faUserPlus
  );
}
