name: Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      # Several packages depend on 'which'. That package has SSL issues as of July 2025.
      run: npm set strict-ssl false && npm ci --force && npm run build:demo

    - name: Deploy Demos to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v1.3.0
      with:
        build_dir: dist/demo
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}